### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by MiroCillik** [keboola/storage-api-cli#10]
```
Component out of memory (exceeded 512m)
```
512MB by tomu malo stacit.

Job:
https://connection.keboola.com/admin/projects/1218/jobs/236121661

Exception:

**Comment by ErikZigo** [comment]
Tohle zaviram. Hadam ze to bylo listovanim verzi velkych konfiguraci. Uz nejaky cas je tam nastaveny nizky limit pro strankovani, ktery to resi.
