### ISSUE TITLE
Failing project-restore tests

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-cli#18]
![image](https://user-images.githubusercontent.com/497675/27839844-64674948-60a9-11e7-986f-108e0a21b21b.png)

**Comment by ondrejhlavacek** [comment]
![image](https://user-images.githubusercontent.com/497675/27849371-a2ab610a-6101-11e7-8d56-98d306cfb5ce.png)

odchytil jsem chybu, a soubor v S3 skutečně je. zapnu logování přístupů a pusím to znovu

**Comment by ondrejhlavacek** [comment]
podle logů není objekt přístupný vteřinu po založení

![image](https://user-images.githubusercontent.com/497675/27852793-5f1f4186-6115-11e7-939b-f03ad9f389c2.png)

**Comment by ondrejhlavacek** [comment]
bude to asi souviset s http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel
https://github.com/aws/aws-sdk-ruby/issues/256

**Comment by ondrejhlavacek** [comment]
bude to asi souviset s http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel
https://github.com/aws/aws-sdk-ruby/issues/256

**Comment by Halama** [comment]
^ jsem predtim procital nekolikrat a z toho jsem pochopil ze ho vzdycky hned prectes po zalozeni.

**Comment by ondrejhlavacek** [comment]
to nechápu? 
ale fixnu to tak, že se fixtures do S3 budou nahrávat odděleně od spouštění testů, prodleva mezi tím by to měla fixnout

**Comment by ondrejhlavacek** [comment]
fixed by #19
