### ISSUE TITLE
Project backup - broken configurations JSON

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-cli#27]
![image](https://user-images.githubusercontent.com/903531/36305844-9bd4177a-1315-11e8-9634-221fff0976a3.png)

```
Warning: Invalid argument supplied for foreach() in /home/vendor/keboola/storage-api-cli/src/Keboola/StorageApi/Cli/Command/BackupProject.php on line 121 #6
 ```
Component just logs warning and continue in execution.

**Comment by Halama** [comment]
This method https://github.com/keboola/storage-api-cli/blob/ec63b80cd44ca8c4eab834b7989f614bc50686f2/src/Keboola/StorageApi/Cli/Command/BackupProject.php#L118 downloads only part of JSON response!

**Comment by ondrejhlavacek** [comment]
It's covered by tests, so it should be easy to simulate. Buffer size or something similar?

**Comment by Halama** [comment]
I have simulated it, it does this everytime for my project. I am moving to SAPI client.

**Comment by Halama** [comment]
When I change the image to standard non-alpine `php:7.1` it works.

**Comment by Halama** [comment]
When i Use in client `sink` parameter it works also on alpine http://docs.guzzlephp.org/en/stable/request-options.html#sink

**Comment by Halama** [comment]
It will be fixed by using standard json client response withou storing into file. If there will be memory issue we'll separate it to multiple API call for each configuration.

**Comment by Halama** [comment]
There is a problem with array conversion in get response https://github.com/keboola/storage-api-cli/blob/ec63b80cd44ca8c4eab834b7989f614bc50686f2/src/Keboola/StorageApi/Cli/Command/BackupProject.php#L107

**Comment by Halama** [comment]
If I change SAPI client's code exactly to this it start works http://docs.guzzlephp.org/en/latest/request-options.html#stream

**Comment by Halama** [comment]
With this SAPI Client branch used tests pass. https://github.com/keboola/storage-api-php-client/pull/184
