### ISSUE TITLE
Add phar self-update

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-cli#3]
https://github.com/kherge/Amend

**Comment by odinuv** [comment]
seems to be almost dead https://github.com/box-project/amend

**Comment by Halama** [comment]
je to starý. Možná bych se na phar úplně vyprdnul a releasoval to spíš jako docker image. Stejně jsme to udělali tady https://github.com/keboola/developer-portal-cli

**Comment by odinuv** [comment]
Docker image v https://github.com/keboola/storage-api-cli/commit/edfed30efc350bc17fc74280ea5030b00e7861a1

na amend kasleme
